"""
Dashboard generation for interactive result exploration.

Creates Streamlit and Dash applications from analysis results.
"""

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any


@dataclass
class DashboardConfig:
    """Configuration for dashboard generation."""

    title: str = "BioAgent Analysis Dashboard"
    theme: str = "light"
    port: int = 8501
    data_path: str | None = None
    include_sidebar: bool = True
    include_download: bool = True


class DashboardGenerator:
    """
    Generate interactive dashboards from analysis results.

    Supports:
    - Streamlit applications
    - Dash/Plotly applications
    """

    def __init__(self, framework: str = "streamlit", config: DashboardConfig | None = None):
        """
        Initialize dashboard generator.

        Args:
            framework: Dashboard framework ("streamlit" or "dash")
            config: Dashboard configuration
        """
        self.framework = framework.lower()
        self.config = config or DashboardConfig()

        if self.framework not in ("streamlit", "dash"):
            raise ValueError(f"Unsupported framework: {framework}")

    def generate_deseq2_dashboard(
        self,
        data_path: str,
        output_path: str | None = None,
    ) -> str:
        """
        Generate a dashboard for DESeq2 results exploration.

        Args:
            data_path: Path to DESeq2 results file
            output_path: Output file path

        Returns:
            Path to generated dashboard file
        """
        if self.framework == "streamlit":
            code = self._streamlit_deseq2(data_path)
        else:
            code = self._dash_deseq2(data_path)

        if output_path is None:
            ext = ".py"
            output_path = f"deseq2_dashboard{ext}"

        return self._save(code, output_path)

    def _streamlit_deseq2(self, data_path: str) -> str:
        """Generate Streamlit dashboard for DESeq2 results."""
        return f'''"""
DESeq2 Results Dashboard
Generated by BioAgent on {datetime.now().strftime('%Y-%m-%d')}

Run with: streamlit run {Path(data_path).stem}_dashboard.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

# Page config
st.set_page_config(
    page_title="{self.config.title}",
    page_icon="🧬",
    layout="wide",
)

# Title
st.title("🧬 {self.config.title}")
st.markdown("Interactive exploration of differential expression results")

# Load data
@st.cache_data
def load_data():
    return pd.read_csv("{data_path}")

data = load_data()

# Sidebar filters
st.sidebar.header("Filters")

# P-value threshold
pval_threshold = st.sidebar.slider(
    "Adjusted p-value threshold",
    min_value=0.001,
    max_value=0.1,
    value=0.05,
    step=0.001,
)

# Fold change threshold
fc_threshold = st.sidebar.slider(
    "log2 Fold Change threshold",
    min_value=0.0,
    max_value=5.0,
    value=1.0,
    step=0.1,
)

# Filter data
if 'padj' in data.columns:
    pval_col = 'padj'
elif 'pvalue' in data.columns:
    pval_col = 'pvalue'
else:
    pval_col = data.columns[data.columns.str.contains('pval', case=False)][0]

if 'log2FoldChange' in data.columns:
    fc_col = 'log2FoldChange'
else:
    fc_col = data.columns[data.columns.str.contains('fold|fc', case=False)][0]

# Classify genes
data['significance'] = 'NS'
data.loc[(data[fc_col] >= fc_threshold) & (data[pval_col] <= pval_threshold), 'significance'] = 'Up'
data.loc[(data[fc_col] <= -fc_threshold) & (data[pval_col] <= pval_threshold), 'significance'] = 'Down'

sig_up = (data['significance'] == 'Up').sum()
sig_down = (data['significance'] == 'Down').sum()

# Metrics
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Genes", len(data))
col2.metric("Significant", sig_up + sig_down)
col3.metric("Up-regulated", sig_up)
col4.metric("Down-regulated", sig_down)

# Tabs
tab1, tab2, tab3, tab4 = st.tabs(["Volcano Plot", "MA Plot", "Data Table", "Gene Search"])

with tab1:
    st.subheader("Volcano Plot")

    # Calculate -log10(p-value)
    data['neg_log10_pval'] = -np.log10(data[pval_col].clip(lower=1e-300))

    fig = px.scatter(
        data,
        x=fc_col,
        y='neg_log10_pval',
        color='significance',
        color_discrete_map={{'Up': '#E64B35', 'Down': '#4DBBD5', 'NS': '#CCCCCC'}},
        hover_data=['gene'] if 'gene' in data.columns else None,
        title='Volcano Plot',
    )

    # Add threshold lines
    fig.add_hline(y=-np.log10(pval_threshold), line_dash="dash", line_color="gray")
    fig.add_vline(x=fc_threshold, line_dash="dash", line_color="gray")
    fig.add_vline(x=-fc_threshold, line_dash="dash", line_color="gray")

    fig.update_layout(
        xaxis_title="log₂(Fold Change)",
        yaxis_title="-log₁₀(adjusted p-value)",
        height=600,
    )

    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("MA Plot")

    if 'baseMean' in data.columns:
        mean_col = 'baseMean'
    else:
        mean_col = data.columns[data.columns.str.contains('mean|avg', case=False)][0] if any(data.columns.str.contains('mean|avg', case=False)) else None

    if mean_col:
        data['log10_mean'] = np.log10(data[mean_col].clip(lower=1))

        fig_ma = px.scatter(
            data,
            x='log10_mean',
            y=fc_col,
            color='significance',
            color_discrete_map={{'Up': '#E64B35', 'Down': '#4DBBD5', 'NS': '#CCCCCC'}},
            title='MA Plot',
        )

        fig_ma.add_hline(y=0, line_color="gray")
        fig_ma.update_layout(
            xaxis_title="log₁₀(Mean Expression)",
            yaxis_title="log₂(Fold Change)",
            height=600,
        )

        st.plotly_chart(fig_ma, use_container_width=True)
    else:
        st.warning("baseMean column not found for MA plot")

with tab3:
    st.subheader("Data Table")

    # Filter options
    show_option = st.radio(
        "Show:",
        ["All genes", "Significant only", "Up-regulated", "Down-regulated"],
        horizontal=True,
    )

    if show_option == "Significant only":
        display_data = data[data['significance'] != 'NS']
    elif show_option == "Up-regulated":
        display_data = data[data['significance'] == 'Up']
    elif show_option == "Down-regulated":
        display_data = data[data['significance'] == 'Down']
    else:
        display_data = data

    st.dataframe(
        display_data.sort_values(pval_col),
        use_container_width=True,
        height=400,
    )

    # Download button
    csv = display_data.to_csv(index=False)
    st.download_button(
        "Download filtered data",
        csv,
        "filtered_results.csv",
        "text/csv",
    )

with tab4:
    st.subheader("Gene Search")

    if 'gene' in data.columns:
        search_term = st.text_input("Search for gene(s) (comma-separated):")

        if search_term:
            genes = [g.strip().upper() for g in search_term.split(",")]
            results = data[data['gene'].str.upper().isin(genes)]

            if len(results) > 0:
                st.dataframe(results)
            else:
                st.warning("No genes found matching your search")
    else:
        st.info("Gene column not found in data")

# Footer
st.markdown("---")
st.markdown("*Generated by BioAgent*")
'''

    def _dash_deseq2(self, data_path: str) -> str:
        """Generate Dash dashboard for DESeq2 results."""
        return f'''"""
DESeq2 Results Dashboard (Dash/Plotly)
Generated by BioAgent on {datetime.now().strftime('%Y-%m-%d')}

Run with: python {Path(data_path).stem}_dashboard.py
"""

import dash
from dash import dcc, html, dash_table, Input, Output, State
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

# Load data
data = pd.read_csv("{data_path}")

# Determine column names
pval_col = 'padj' if 'padj' in data.columns else 'pvalue'
fc_col = 'log2FoldChange' if 'log2FoldChange' in data.columns else data.columns[1]

# Calculate -log10(p-value)
data['neg_log10_pval'] = -np.log10(data[pval_col].clip(lower=1e-300))

# Initialize app
app = dash.Dash(__name__, title="{self.config.title}")

app.layout = html.Div([
    html.H1("{self.config.title}", style={{'textAlign': 'center'}}),

    html.Div([
        html.Div([
            html.Label("P-value threshold:"),
            dcc.Slider(
                id='pval-slider',
                min=-3,
                max=-1,
                value=-1.3,  # 0.05
                marks={{i: f'10^{{i}}' for i in range(-3, 0)}},
                step=0.1,
            ),
        ], style={{'width': '45%', 'display': 'inline-block', 'padding': '10px'}}),

        html.Div([
            html.Label("Fold change threshold:"),
            dcc.Slider(
                id='fc-slider',
                min=0,
                max=3,
                value=1,
                marks={{i: str(i) for i in range(4)}},
                step=0.1,
            ),
        ], style={{'width': '45%', 'display': 'inline-block', 'padding': '10px'}}),
    ]),

    html.Div(id='metrics', style={{'padding': '20px'}}),

    dcc.Tabs([
        dcc.Tab(label='Volcano Plot', children=[
            dcc.Graph(id='volcano-plot', style={{'height': '600px'}}),
        ]),
        dcc.Tab(label='Data Table', children=[
            dash_table.DataTable(
                id='data-table',
                columns=[{{'name': i, 'id': i}} for i in data.columns],
                data=data.to_dict('records'),
                page_size=20,
                filter_action='native',
                sort_action='native',
                export_format='csv',
                style_table={{'overflowX': 'auto'}},
            ),
        ]),
    ]),

    html.Footer("Generated by BioAgent", style={{'textAlign': 'center', 'padding': '20px'}}),
])


@app.callback(
    [Output('volcano-plot', 'figure'),
     Output('metrics', 'children')],
    [Input('pval-slider', 'value'),
     Input('fc-slider', 'value')]
)
def update_plot(pval_log, fc_thresh):
    pval_thresh = 10 ** pval_log

    # Classify
    df = data.copy()
    df['significance'] = 'NS'
    df.loc[(df[fc_col] >= fc_thresh) & (df[pval_col] <= pval_thresh), 'significance'] = 'Up'
    df.loc[(df[fc_col] <= -fc_thresh) & (df[pval_col] <= pval_thresh), 'significance'] = 'Down'

    sig_up = (df['significance'] == 'Up').sum()
    sig_down = (df['significance'] == 'Down').sum()

    # Volcano plot
    fig = px.scatter(
        df,
        x=fc_col,
        y='neg_log10_pval',
        color='significance',
        color_discrete_map={{'Up': '#E64B35', 'Down': '#4DBBD5', 'NS': '#CCCCCC'}},
    )

    fig.add_hline(y=-np.log10(pval_thresh), line_dash="dash")
    fig.add_vline(x=fc_thresh, line_dash="dash")
    fig.add_vline(x=-fc_thresh, line_dash="dash")

    fig.update_layout(
        xaxis_title="log₂(Fold Change)",
        yaxis_title="-log₁₀(adjusted p-value)",
    )

    metrics = html.Div([
        html.Span(f"Total: {{len(df)}} | ", style={{'fontWeight': 'bold'}}),
        html.Span(f"Significant: {{sig_up + sig_down}} | "),
        html.Span(f"Up: {{sig_up}} | ", style={{'color': '#E64B35'}}),
        html.Span(f"Down: {{sig_down}}", style={{'color': '#4DBBD5'}}),
    ])

    return fig, metrics


if __name__ == '__main__':
    app.run_server(debug=True, port={self.config.port})
'''

    def generate_expression_dashboard(
        self,
        counts_path: str,
        metadata_path: str | None = None,
        output_path: str | None = None,
    ) -> str:
        """
        Generate dashboard for expression data exploration.

        Args:
            counts_path: Path to counts matrix
            metadata_path: Path to sample metadata
            output_path: Output file path

        Returns:
            Path to generated dashboard file
        """
        if self.framework == "streamlit":
            code = self._streamlit_expression(counts_path, metadata_path)
        else:
            code = self._dash_expression(counts_path, metadata_path)

        if output_path is None:
            output_path = "expression_dashboard.py"

        return self._save(code, output_path)

    def _streamlit_expression(self, counts_path: str, metadata_path: str | None) -> str:
        """Generate Streamlit dashboard for expression data."""
        metadata_load = f'metadata = pd.read_csv("{metadata_path}")' if metadata_path else 'metadata = None'

        return f'''"""
Expression Data Dashboard
Generated by BioAgent
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

st.set_page_config(page_title="Expression Dashboard", layout="wide")
st.title("🧬 Expression Data Explorer")

@st.cache_data
def load_data():
    counts = pd.read_csv("{counts_path}", index_col=0)
    {metadata_load}
    return counts, metadata

counts, metadata = load_data()

# Sidebar
st.sidebar.header("Settings")
log_transform = st.sidebar.checkbox("Log2 transform", value=True)
top_n_genes = st.sidebar.slider("Top variable genes", 100, 5000, 1000)

# Process data
if log_transform:
    expression = np.log2(counts + 1)
else:
    expression = counts

# Select top variable genes
gene_var = expression.var(axis=1)
top_genes = gene_var.nlargest(top_n_genes).index
expression_subset = expression.loc[top_genes]

# Tabs
tab1, tab2, tab3 = st.tabs(["PCA", "Heatmap", "Gene Explorer"])

with tab1:
    st.subheader("PCA Analysis")

    # Perform PCA
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(expression_subset.T)
    pca = PCA(n_components=2)
    pcs = pca.fit_transform(scaled_data)

    pca_df = pd.DataFrame({{
        'PC1': pcs[:, 0],
        'PC2': pcs[:, 1],
        'Sample': expression.columns
    }})

    if metadata is not None:
        pca_df = pca_df.merge(metadata, left_on='Sample', right_index=True, how='left')
        color_col = st.selectbox("Color by:", metadata.columns)
    else:
        color_col = None

    fig = px.scatter(
        pca_df,
        x='PC1',
        y='PC2',
        color=color_col,
        hover_data=['Sample'],
        title=f'PCA ({{pca.explained_variance_ratio_[0]*100:.1f}}% + {{pca.explained_variance_ratio_[1]*100:.1f}}%)',
    )
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("Expression Heatmap")

    n_genes_heatmap = st.slider("Genes to show", 10, 100, 50)
    top_var_genes = gene_var.nlargest(n_genes_heatmap).index

    fig_heatmap = px.imshow(
        expression.loc[top_var_genes],
        color_continuous_scale='RdBu_r',
        aspect='auto',
    )
    st.plotly_chart(fig_heatmap, use_container_width=True)

with tab3:
    st.subheader("Gene Expression")

    gene_search = st.text_input("Search gene:")
    if gene_search and gene_search in expression.index:
        gene_data = expression.loc[gene_search]

        fig_gene = px.bar(
            x=gene_data.index,
            y=gene_data.values,
            title=f'{{gene_search}} Expression',
        )
        st.plotly_chart(fig_gene, use_container_width=True)

st.markdown("---")
st.markdown("*Generated by BioAgent*")
'''

    def _dash_expression(self, counts_path: str, metadata_path: str | None) -> str:
        """Generate Dash dashboard for expression data."""
        return f'''"""
Expression Data Dashboard (Dash)
Generated by BioAgent
"""

import dash
from dash import dcc, html, Input, Output
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Load data
counts = pd.read_csv("{counts_path}", index_col=0)
expression = np.log2(counts + 1)

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Expression Data Explorer"),

    dcc.Tabs([
        dcc.Tab(label='PCA', children=[
            dcc.Graph(id='pca-plot'),
        ]),
        dcc.Tab(label='Heatmap', children=[
            dcc.Graph(id='heatmap'),
        ]),
    ]),
])

@app.callback(Output('pca-plot', 'figure'), Input('pca-plot', 'id'))
def update_pca(_):
    scaler = StandardScaler()
    scaled = scaler.fit_transform(expression.T)
    pca = PCA(n_components=2)
    pcs = pca.fit_transform(scaled)

    fig = px.scatter(x=pcs[:, 0], y=pcs[:, 1], text=expression.columns)
    fig.update_layout(xaxis_title='PC1', yaxis_title='PC2')
    return fig

@app.callback(Output('heatmap', 'figure'), Input('heatmap', 'id'))
def update_heatmap(_):
    top_genes = expression.var(axis=1).nlargest(50).index
    fig = px.imshow(expression.loc[top_genes], color_continuous_scale='RdBu_r')
    return fig

if __name__ == '__main__':
    app.run_server(debug=True)
'''

    def _save(self, code: str, path: str) -> str:
        """Save dashboard code to file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        if not path.suffix:
            path = path.with_suffix(".py")

        path.write_text(code, encoding="utf-8")
        return str(path.absolute())


def create_dashboard(
    dashboard_type: str,
    data_path: str,
    framework: str = "streamlit",
    output_path: str | None = None,
    **kwargs,
) -> str:
    """
    Create a dashboard from analysis results.

    Args:
        dashboard_type: Type of dashboard (deseq2, expression, enrichment)
        data_path: Path to data file
        framework: Dashboard framework (streamlit or dash)
        output_path: Output file path
        **kwargs: Additional parameters

    Returns:
        Path to generated dashboard file
    """
    generator = DashboardGenerator(framework=framework)

    if dashboard_type == "deseq2":
        return generator.generate_deseq2_dashboard(data_path, output_path)
    elif dashboard_type == "expression":
        metadata_path = kwargs.get("metadata_path")
        return generator.generate_expression_dashboard(data_path, metadata_path, output_path)
    else:
        raise ValueError(f"Unknown dashboard type: {dashboard_type}")
